import type { Block, Content, MediaAsset, Project } from "./types";

/**
 * Initial content. Everything here is editable in /admin.
 * Projects flagged `demo: true` use placeholder media and neutral copy —
 * replace them with the real case material. No results are invented:
 * `outcomes` only carries figures Felipe supplied himself.
 */

const T = "2026-10-08T00:00:00.000Z";

const ph = (id: string, file: string, w: number, h: number, alt: string, extra: Partial<MediaAsset> = {}): MediaAsset => ({
  id,
  kind: "image",
  src: `/placeholders/${file}`,
  alt,
  width: w,
  height: h,
  mime: "image/jpeg",
  origin: "placeholder",
  createdAt: T,
  ...extra,
});

const media: MediaAsset[] = [
  ph("ph-hero-d", "hero-desktop.jpg", 2400, 1350, "Placeholder for Felipe Pidi's hero portrait (desktop)"),
  ph("ph-hero-m", "hero-mobile.jpg", 1080, 1920, "Placeholder for Felipe Pidi's hero portrait (mobile)"),
  ph("ph-about", "about.jpg", 1600, 2000, "Placeholder for a black-and-white portrait of Felipe Pidi"),
  ph("ph-nazca", "nazca.jpg", 2520, 1080, "Placeholder key visual — orange sun over dunes"),
  ph("ph-diniz", "diniz.jpg", 1600, 2000, "Placeholder campaign visual in red"),
  ph("ph-styles", "styles.jpg", 1600, 1600, "Placeholder generative study in mint and blue"),
  ph("ph-mercado", "mercado.jpg", 2400, 1350, "Placeholder campaign visual in blue"),
  ph("ph-kfc", "kfc.jpg", 2400, 1350, "Placeholder art direction frame in red"),
  ph("ph-film", "film.jpg", 2520, 1080, "Placeholder film still"),
  ph("ph-still-a", "still-a.jpg", 1800, 1200, "Placeholder gallery still, 3:2"),
  ph("ph-still-b", "still-b.jpg", 1600, 2000, "Placeholder gallery still, 4:5"),
  ph("ph-still-c", "still-c.jpg", 1600, 1600, "Placeholder gallery still, 1:1"),
  ph("ph-reel-poster", "reel-poster.jpg", 1280, 548, "Placeholder reel poster frame"),
  {
    id: "ph-reel",
    kind: "video",
    src: "/placeholders/reel.mp4",
    posterId: "ph-reel-poster",
    alt: "Placeholder reel — slow push-in on a desert sun",
    width: 1280,
    height: 548,
    mime: "video/mp4",
    origin: "placeholder",
    createdAt: T,
  },
];

type NoId<T> = T extends unknown ? Omit<T, "id"> : never;
const b = (blocks: NoId<Block>[], prefix: string): Block[] =>
  blocks.map((blk, i) => ({ ...blk, id: `${prefix}-b${i + 1}` }) as Block);

const base = (p: Partial<Project> & Pick<Project, "id" | "slug" | "title" | "year">): Project => ({
  subtitle: "",
  client: "",
  role: "",
  disciplines: [],
  categoryIds: [],
  accent: "#EF2917",
  coverFocus: "center",
  featured: false,
  featuredLayout: "fullbleed",
  archiveShape: "landscape",
  published: true,
  order: 0,
  overview: "",
  challenge: "",
  concept: "",
  process: "",
  outcomes: "",
  credits: [],
  blocks: [],
  demo: true,
  createdAt: T,
  updatedAt: T,
  ...p,
});

const projects: Project[] = [
  base({
    id: "p-nazca",
    slug: "nazca-experimente-sentir",
    title: "Nazca",
    subtitle: "Experimente Sentir",
    client: "Nazca",
    year: 2026,
    role: "Creative Direction",
    disciplines: ["Creative Direction", "Campaign", "Art Direction"],
    categoryIds: ["c-direction"],
    accent: "#FF6030",
    coverId: "ph-nazca",
    coverVideoId: "ph-reel",
    featured: true,
    featuredLayout: "fullbleed",
    archiveShape: "landscape",
    order: 1,
    overview: "Demo copy — a campaign built around the line “Experimente Sentir”. Replace this paragraph with the real overview in /admin.",
    challenge: "Describe the brief and the problem the campaign had to solve.",
    concept: "Describe the creative idea and the visual strategy behind it.",
    process: "Research, references, concept development, direction and production.",
    credits: [{ role: "Creative Direction", name: "Felipe Pidi" }],
    blocks: b(
      [
        { type: "text", heading: "The idea", body: "A large editorial statement about the campaign. Edit or remove this block in the case study editor.", size: "xl" },
        { type: "video", assetId: "ph-reel", caption: "Reel — placeholder", autoplay: true },
        { type: "asymmetric", assetIds: ["ph-still-b", "ph-still-a", "ph-still-c"] },
        { type: "imageText", assetId: "ph-still-a", heading: "Frame by frame", text: "Pair a key frame with a short note on direction, light or casting.", side: "right" },
        { type: "filmstrip", assetIds: ["ph-still-a", "ph-nazca", "ph-still-c", "ph-film", "ph-still-b"] },
        { type: "grid3", assetIds: ["ph-still-c", "ph-still-b", "ph-still-c"] },
      ],
      "nazca",
    ),
  }),
  base({
    id: "p-diniz",
    slug: "oticas-diniz-national-campaign",
    title: "Óticas Diniz",
    subtitle: "National Campaign",
    client: "Óticas Diniz",
    year: 2025,
    role: "AI-Driven Lead Design · DDAO Creative Lab",
    disciplines: ["Campaign", "Art Direction", "Generative AI"],
    categoryIds: ["c-direction", "c-ai"],
    accent: "#EF2917",
    coverId: "ph-diniz",
    featured: true,
    featuredLayout: "split",
    archiveShape: "poster",
    order: 2,
    overview: "Demo copy — national campaign for Óticas Diniz, developed at DDAO Creative Lab. Replace with the real case.",
    credits: [{ role: "AI-Driven Lead Designer", name: "Felipe Pidi" }],
    blocks: b(
      [
        { type: "grid2", assetIds: ["ph-diniz", "ph-still-b"] },
        { type: "gallery", assetIds: ["ph-still-a", "ph-still-b", "ph-still-c", "ph-diniz"] },
      ],
      "diniz",
    ),
  }),
  base({
    id: "p-styles",
    slug: "node-styles",
    title: "Node Styles",
    subtitle: "Visual styles as reusable pipelines",
    client: "Jotacom",
    year: 2026,
    role: "AI Creative Lead",
    disciplines: ["Generative AI", "Creative Systems", "Workflow Design"],
    categoryIds: ["c-ai", "c-branding"],
    accent: "#A8F5E5",
    coverId: "ph-styles",
    featured: true,
    featuredLayout: "poster",
    archiveShape: "square",
    order: 3,
    overview: "A library of visual styles built as node-based pipelines, so other designers on the team can reproduce the same aesthetic with consistency.",
    outcomes: "Around 25 visual styles built as node pipelines.\nCreative route time down from about 2 hours to 20–30 minutes.",
    credits: [{ role: "AI Creative Lead", name: "Felipe Pidi" }],
    blocks: b(
      [
        { type: "text", body: "Taste, encoded. Each style is a pipeline anyone on the squad can run.", size: "xl" },
        { type: "grid3", assetIds: ["ph-styles", "ph-still-c", "ph-styles"] },
      ],
      "styles",
    ),
  }),
  base({
    id: "p-meli",
    slug: "mercado-livre",
    title: "Mercado Livre",
    subtitle: "Campaigns",
    client: "Mercado Livre",
    year: 2026,
    role: "AI Creative Lead · Jotacom",
    disciplines: ["Campaign", "Generative AI"],
    categoryIds: ["c-direction", "c-ai"],
    accent: "#138FE0",
    coverId: "ph-mercado",
    archiveShape: "landscape",
    order: 5,
    overview: "Demo copy — campaign work for Mercado Livre at Jotacom. Replace with the real case.",
  }),
  base({
    id: "p-kfc",
    slug: "kfc",
    title: "KFC",
    subtitle: "Art Direction",
    client: "KFC",
    year: 2021,
    role: "Senior Art Director · The Heart",
    disciplines: ["Art Direction", "Campaign"],
    categoryIds: ["c-direction"],
    accent: "#EF2917",
    coverId: "ph-kfc",
    archiveShape: "type",
    order: 6,
    overview: "Demo copy — art direction for KFC at The Heart. Replace with the real case.",
  }),
  base({
    id: "p-duo",
    slug: "duolingo",
    title: "Duolingo",
    subtitle: "Campaign",
    client: "Duolingo",
    year: 2026,
    role: "AI Creative Lead · Jotacom",
    disciplines: ["Campaign", "Generative AI"],
    categoryIds: ["c-direction", "c-ai"],
    accent: "#A8F5E5",
    coverId: "ph-still-c",
    archiveShape: "square",
    order: 7,
    overview: "Demo copy — campaign work for Duolingo at Jotacom. Replace with the real case.",
  }),
];

export const seedContent: Content = {
  version: 1,
  settings: {
    name: { first: "Felipe", last: "Pidi", full: "Felipe Pidi" },
    role: "Associate Creative Director & AI Creative Lead",
    hero: {
      roleLines: ["ACD &", "AI Creative Lead"],
      lead: "Branding, 360° campaigns and node-based AI pipelines — 12+ years turning strategy into visual systems whole teams can run.",
      meta: ["Based in São Paulo, Brazil", "Available worldwide", "Selected works / 2014—2026"],
      cta: "Explore the work",
      portraitDesktopId: "ph-hero-d",
      portraitMobileId: "ph-hero-m",
    },
    selectedWork: {
      headline: ["Selected", "Works."],
      subtitle: "Campaigns, brand systems and AI-driven production — directed from concept to craft.",
      featuredOrder: ["p-nazca", "p-diniz", "p-styles"],
    },
    archive: { headline: ["The", "Archive."], subtitle: "Different disciplines. One creative vision." },
    photography: {
      headline: ["Photography"],
      subtitle: "Portrait sessions shot as @olhosdefelipe — light, color and attitude, frame by frame.",
      photoIds: [],
    },
    about: {
      headline: ["The person", "behind the work."],
      portraitId: "ph-about",
      bio: [
        "Felipe Pidi has been building creative processes since 2014 — but the work was never only about making good pieces. Across 12+ years in advertising, branding and 360° campaigns, he learned to turn strategy into visual language, and visual language into something a whole team can execute with consistency.",
        "He has worked on integrated campaigns, films, retail and brand identities, on productions with crews of 30+. As Head of Design at Agência Ecco he led a team of 10+ designers and redesigned the flow between creative, planning and accounts — cutting rework by 28% and speeding up delivery by 25%.",
        "Today, as AI Creative Lead at Jotacom, he applies the same logic to AI. Not just generating images, but building repeatable creative systems: around 25 visual styles structured as node pipelines in Flora and Magnific, turning ~2 hours of trial and error into 20–30 minutes while protecting art direction and brand identity. AI doesn't replace creative thinking — it demands more direction.",
        "Brands along the way: Mercado Livre, UOL, NIO, Duolingo, KFC, Mercedes-Benz, PwC, CPFL, Stabilo, Uni-ball, Posca, Dr. Scholl's, Banco24Horas, Linx, Starbucks, Pizza Hut and Óticas Diniz.",
      ],
      disciplines: ["Creative Direction", "Art Direction", "Brand Identity", "AI Creative Systems", "Design Leadership", "Set & Film Direction"],
      metrics: [
        { value: "12+", label: "Years in advertising, branding & 360° campaigns" },
        { value: "120+", label: "Campaigns delivered" },
        { value: "15+", label: "Brand identity systems" },
        { value: "10+", label: "Designers led as Head of Design" },
        { value: "−28%", label: "Rework after redesigning the creative workflow" },
        { value: "+25%", label: "Faster delivery across the design team" },
      ],
    },
    contact: {
      headline: ["Let's make", "something", "unforgettable."],
      copy: "Need a creative lead who designs the workflow, not just the work? Let's talk — campaigns, brands and AI production at scale.",
      email: "felipe.luiz27@hotmail.com",
      location: "São Paulo, Brazil",
      availability: "Freelance & full-time · Remote worldwide",
    },
    social: {
      linkedin: "https://www.linkedin.com/in/felipe-luiz-78043597/",
      behance: "https://www.behance.net/felipeluiz",
      instagram: "https://www.instagram.com/olhosdefelipe/",
      whatsapp: "5511983829395",
    },
    cv: {},
    footer: { signature: "Felipe Pidi © 2026", tagline: "Made with intention." },
    seo: {
      title: "Felipe Pidi — ACD & AI Creative Lead",
      description:
        "Portfolio of Felipe Pidi, Associate Creative Director and AI Creative Lead in São Paulo. 12+ years in branding, 360° campaigns and node-based AI production pipelines.",
    },
  },
  categories: [
    { id: "c-direction", slug: "direction", index: "01", title: "Creative Direction & Campaigns", filterLabel: "Direction", description: "Campaign development, creative concepts, advertising, art direction and integrated communication.", order: 1 },
    { id: "c-branding", slug: "branding", index: "02", title: "Brand Identity & Design Systems", filterLabel: "Branding", description: "Branding, identity systems, visual languages, guidelines and graphic design.", order: 2 },
    { id: "c-ai", slug: "generative-ai", index: "03", title: "Generative AI & Experimentation", filterLabel: "Generative AI", description: "AI workflows, creative automation, visual exploration, generative production and experimental projects.", order: 3 },
    { id: "c-motion", slug: "motion", index: "04", title: "Film, Motion & Visual Storytelling", filterLabel: "Motion", description: "Film direction, motion design, audiovisual production and visual narratives.", order: 4 },
  ],
  projects,
  media,
};
